require: rubocop-rspec

AllCops:
  NewCops: enable

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - "app.rb"

Style/StringLiterals:
  Enabled: false